### ISSUE TITLE
error for bamboo-haproy

### ISSUE THREAD

**Issue by mihai-satmarean** [theclaymethod/Foundry-vagrant-mesos-kafka-cluster#1]
When building the environment we get this error:
TASK: [bamboo-haproxy | Build bamboo image] **********************************\* 
failed: [100.0.10.102] => {"failed": true, "parsed": false}
SUDO-SUCCESS-gygrgcpeatjghxdfsyqbeefhjlvjjmra
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1415895628.48-91606373400347/docker", line 2419, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1415895628.48-91606373400347/docker", line 802, in main
    manager.start_containers(deployed_containers)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1415895628.48-91606373400347/docker", line 661, in start_containers
    self.client.start(i['Id'], **params)
TypeError: start() got an unexpected keyword argument 'network_mode'

FATAL: all hosts have already failed -- aborting

Otherwise, great work and thank you!

**Comment by theclaymethod** [comment]
I'll take a look. I temporarily disabled it since it added quite a bit to the provisioning time, and I wanted to get HDFS and spark running, so something may have broken along the way.

Thanks!

**Comment by theclaymethod** [comment]
Figured out that the issue was related to comma injection in the ENV variable for Docker Containers.
So the original env: BAMBOO_ZK_HOST={{zk_servers_noproto}} due to the way the env is split on commas: http://comments.gmane.org/gmane.comp.sysutils.ansible/12118

The fix is currently in the dev branch of ansible. I am looking for a workaround.
